/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.JInternalFrame;

public class FormPrincipal extends javax.swing.JFrame {

    
    public FormPrincipal() {
        initComponents();
        
        this.setTitle("Controle de Funcionarios");
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        areaTrabalho = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuarquivo = new javax.swing.JMenu();
        menucadastro = new javax.swing.JMenu();
        menucadastroempresa = new javax.swing.JMenuItem();
        menucadastrofuncionario = new javax.swing.JMenuItem();
        menupesquisa = new javax.swing.JMenu();
        menupesquisaempresa = new javax.swing.JMenuItem();
        menupesquisafuncionario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout areaTrabalhoLayout = new javax.swing.GroupLayout(areaTrabalho);
        areaTrabalho.setLayout(areaTrabalhoLayout);
        areaTrabalhoLayout.setHorizontalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        areaTrabalhoLayout.setVerticalGroup(
            areaTrabalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        menuarquivo.setText("Arquivo");
        jMenuBar1.add(menuarquivo);

        menucadastro.setText("Cadastro");

        menucadastroempresa.setText("Empresa");
        menucadastroempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastroempresaActionPerformed(evt);
            }
        });
        menucadastro.add(menucadastroempresa);

        menucadastrofuncionario.setText("Funcionario");
        menucadastrofuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menucadastrofuncionarioActionPerformed(evt);
            }
        });
        menucadastro.add(menucadastrofuncionario);

        jMenuBar1.add(menucadastro);

        menupesquisa.setText("Pesquisa");

        menupesquisaempresa.setText("Empresa");
        menupesquisaempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupesquisaempresaActionPerformed(evt);
            }
        });
        menupesquisa.add(menupesquisaempresa);

        menupesquisafuncionario.setText("Funcionario");
        menupesquisafuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menupesquisafuncionarioActionPerformed(evt);
            }
        });
        menupesquisa.add(menupesquisafuncionario);

        jMenuBar1.add(menupesquisa);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(areaTrabalho)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menucadastroempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastroempresaActionPerformed
        
        abrirForm(new FormCadastroEmpresa());      
    }//GEN-LAST:event_menucadastroempresaActionPerformed

    private void menupesquisaempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupesquisaempresaActionPerformed
        
        abrirForm(new FormPesquisaEmpresa());
        
    }//GEN-LAST:event_menupesquisaempresaActionPerformed

    private void menucadastrofuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menucadastrofuncionarioActionPerformed
        
        abrirForm(new FormCadastroFuncionario());
        
    }//GEN-LAST:event_menucadastrofuncionarioActionPerformed

    private void menupesquisafuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menupesquisafuncionarioActionPerformed
        
        abrirForm(new FormPesquisaFuncionario());
        
    }//GEN-LAST:event_menupesquisafuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane areaTrabalho;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuarquivo;
    private javax.swing.JMenu menucadastro;
    private javax.swing.JMenuItem menucadastroempresa;
    private javax.swing.JMenuItem menucadastrofuncionario;
    private javax.swing.JMenu menupesquisa;
    private javax.swing.JMenuItem menupesquisaempresa;
    private javax.swing.JMenuItem menupesquisafuncionario;
    // End of variables declaration//GEN-END:variables

     private void abrirForm(JInternalFrame f){
        if (areaTrabalho.getAllFrames().length == 0){
            Dimension d = areaTrabalho.getSize();
            areaTrabalho.add(f);
            f.setLocation( (d.width-f.getSize().width)/2,
                           (d.height-f.getSize().height)/2);
            f.setVisible(true);
        }
    }

}
